[theme]
base = "light"
font = "sans serif"

[server]
headless = true
enableXsrfProtection = true
maxUploadSize = 10

[browser]
gatherUsageStats = false

[runner]
fastReruns = true

[client]
showErrorDetails = true
toolbarMode = "minimal"
